version: '3.7'

services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  expressapi:
    build:
      context: ./expressAPI
    container_name: expressapi
    volumes:
      - ./expressAPI:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
